### ISSUE TITLE
Add basis of nesting grids to getting started material

### ISSUE THREAD

**Issue by steveknoblock** [pure-css/pure-site#330]
I love the simplicity of Pure, but there was nothing on the getting started page about how to nest grids. I had to google for an answer and found it in your blog http://blog.purecss.io/post/69292981583/can-grids-be-nested. It would be nice to place this info with the explanation of the grid basics on the getting started page.

**Comment by redonkulus** [comment]
This is a reasonable request. Will try to get this out soon.
