### ISSUE TITLE
Text Contrast

### ISSUE THREAD

**Issue by Shoeboxam** [pure-css/pure-site#392]
### Description
This is more of a usability suggestion. The base text color is #777 with a light font weight. I find myself squinting when trying to read the documentation, so I edited the body text color to black in the web inspector.

### Expected behavior
Overall the font colors and weights should contrast enough with the background to make them easy to read.

### Actual behavior
Text is difficult to distinguish from the background.

### Steps to Reproduce
View any page of the documentation, EG:
https://purecss.io/buttons/

Thanks for the awesome library!

**Comment by redonkulus** [comment]
Fair enough. You want to open a PR with a darker constrast? I wouldn’t go #000, maybe #333 or #666.

**Comment by redonkulus** [comment]
I’ve just merged https://github.com/pure-css/pure-site/pull/399 which helps with the contrast. Please try it out and reopen if further changes are needed.
