### ISSUE TITLE
Example: Cards? Quoteblocks? MessageBlocks? Codeblocks?

### ISSUE THREAD

**Issue by DonaldTsang** [pure-css/pure-site#403]
### Description

I saw on the website that there are no cards at all in the example/tutorials.
Since all three of these concepts are basically the same common format, is it possible to make something out of it?

**Comment by DonaldTsang** [comment]
Citing https://github.com/pure-css/pure/issues/735

**Comment by DonaldTsang** [comment]
okay this needs a bit of update, because such confusion would cause confusion with new users.

**Comment by redonkulus** [comment]
I’m all for fixing this but it’s going to be community driven. If you want to add a new example to the site I would merge it in.
