### ISSUE TITLE
So 5 years since it was "a good idea" and "closed" list of classes in docs still does not exist?

### ISSUE THREAD

**Issue by alexyuriev** [pure-css/pure-site#424]
I really do not want to be pointing but...

https://github.com/pure-css/pure-site/issues/197 got closed and absorbed into 
 https://github.com/pure-css/pure-site/issues/245

it has been over five years and there's still no such thing as a list of classes together with a quick description of what each class does.

**Comment by redonkulus** [comment]
Would you care to open a PR that lists them all on the site?

**Comment by alexyuriev** [comment]
Not really. My knowledge and understanding of CSS is rather rudimentary and the last thing that I would want to do is to publish my "understanding" of what happens rather than what actually happens.

**Comment by redonkulus** [comment]
But what a good way to learn something new 😉
